language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t okitsnotok/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true okitsnotok/react-test npm test

after_success: 
  - docker build -t okitsnotok/multi-client ./client
  - docker build -t okitsnotok/multi-nginx ./nginx
  - docker build -t okitsnotok/multi-server ./server
  - docker build -t okitsnotok/multi-worker ./worker
  # log in to the docker CLi
  # take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push okitsnotok/multi-client
  - docker push okitsnotok/multi-nginx
  - docker push okitsnotok/multi-server
  - docker push okitsnotok/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-756188756696'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY